version: "3.7"

services:
  erpnext:
    image: frappe/erpnext:develop
    container_name: erpnext
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=default
      - DB_USER=mariadb
      - DB_PASSWORD=Sy9r1WtMu6aJvTR8ldE79
      - REDIS_CACHE=redis://default:pWhfJOxlOlMEb5TmY6OxKojC7MhKbqeQa9U2NYoHaoyQyEq8ByfDt2ODmIyS0HVy@redis:6379
      - REDIS_QUEUE=redis://default:pWhfJOxlOlMEb5TmY6OxKojC7MhKbqeQa9U2NYoHaoyQyEq8ByfDt2ODmIyS0HVy@redis:6379
      - REDIS_SOCKETIO=redis://default:pWhfJOxlOlMEb5TmY6OxKojC7MhKbqeQa9U2NYoHaoyQyEq8ByfDt2ODmIyS0HVy@redis:6379
      - SITE_NAME=speedelog.space
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./erpnext-sites:/home/frappe/frappe-bench/sites
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=lihQtJ69G8a95lBty8ScWU
      - MYSQL_DATABASE=default
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=Sy9r1WtMu6aJvTR8ldE79
    volumes:
      - ./mariadb-data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: redis
    command: redis-server --requirepass pWhfJOxlOlMEb5TmY6OxKojC7MhKbqeQa9U2NYoHaoyQyEq8ByfDt2ODmIyS0HVy
    volumes:
      - ./redis-data:/data
